# Generated by Django 2.1.2 on 2018-11-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181125_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
    ]
