# Generated by Django 2.1.2 on 2018-11-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
    ]
