# Generated by Django 2.1.2 on 2018-11-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20181125_1758'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
    ]
