# Generated by Django 2.1.2 on 2018-11-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20181125_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartty',
            fields=[
                ('item_no', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
    ]
