# Generated by Django 2.1.2 on 2018-11-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_cartty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartty',
            options={},
        ),
    ]
