# Generated by Django 2.1.2 on 2018-11-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20181125_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carttyy',
            fields=[
                ('item_no', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Cartty',
        ),
    ]
