# Generated by Django 2.1.2 on 2018-11-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_abcd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Matches', models.CharField(max_length=10)),
                ('ranking', models.TextField()),
                ('players', models.TextField()),
            ],
        ),
    ]
