# Generated by Django 2.1.2 on 2018-11-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_testrankig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrankig',
            name='odiposition',
        ),
    ]
