# Generated by Django 2.1.2 on 2018-11-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_testrankig_odiposition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrankig',
            old_name='odirating',
            new_name='rating',
        ),
    ]
