# Generated by Django 2.1.2 on 2018-11-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_ground'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
