# Generated by Django 2.1.2 on 2018-11-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_ground_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ame', models.CharField(max_length=10)),
                ('played', models.CharField(max_length=10)),
                ('namewins', models.CharField(max_length=10)),
                ('amewins', models.CharField(max_length=10)),
                ('tie', models.CharField(max_length=10)),
            ],
        ),
    ]
