# Generated by Django 2.1.2 on 2018-11-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_stat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
