# Generated by Django 2.1.2 on 2018-11-27 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
