# Generated by Django 2.1.2 on 2018-11-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_runs_ame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='Scores',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='runs',
            name='ame',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='runs',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='runs',
            name='matches',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='runs',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
