# Generated by Django 2.1.2 on 2018-12-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20181127_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playerstat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ame', models.CharField(max_length=50)),
                ('matches', models.CharField(max_length=50)),
                ('Scores', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
