# Generated by Django 2.1.2 on 2018-12-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_playerstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
