# Generated by Django 2.1.2 on 2018-12-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_remove_ground_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
