# Generated by Django 2.1.2 on 2018-12-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20181204_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
