# Generated by Django 2.1.2 on 2018-12-04 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_auto_20181204_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='bat',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stats',
            name='batt',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stats',
            name='bowl',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stats',
            name='bowll',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stats',
            name='score',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stats',
            name='scoree',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='stats',
            name='name',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, to='products.Teams'),
        ),
    ]
