# Generated by Django 2.1.2 on 2018-12-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20181204_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='bat',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='batt',
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
