# Generated by Django 2.1.2 on 2018-12-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_auto_20181204_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='bowl',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='bowll',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='score',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='scoree',
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
