# Generated by Django 2.1.2 on 2018-12-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_auto_20181204_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='ame',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='stats',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
