# Generated by Django 2.1.2 on 2018-12-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20181204_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='score',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stats',
            name='scoree',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
