# Generated by Django 2.1.2 on 2018-12-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_auto_20181204_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='abcscore',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stats',
            name='bcdscoree',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
