# Generated by Django 2.1.2 on 2018-12-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_auto_20181204_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='runs',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
