# Generated by Django 2.1.2 on 2018-12-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_auto_20181204_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='birthplace',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerstat',
            name='born',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerstat',
            name='profile',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerstat',
            name='teams',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
