# Generated by Django 2.1.2 on 2018-12-04 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_auto_20181204_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstat',
            name='birthplace',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='born',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='teams',
        ),
    ]
