# Generated by Django 2.1.2 on 2018-12-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_auto_20181206_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='abcbat',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='stats',
            name='abcbowl',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='stats',
            name='bcdbatt',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='stats',
            name='bcdbowll',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
